@startuml
class Piece {
    + Piece(type:PieceType, color:Color)
    + <<override>> Equals(obj:object?) : bool
    + <<override>> ToString() : string
    + <<override>> GetHashCode() : int
}
Piece --> "Type" PieceType
Piece --> "Color" Color
@enduml
